language: node_js
node_js:
- '6'
notifications:
  email: true
sudo: required
dist: trusty
env:
  matrix:
  - CXX=g++-4.8
addons:
  sauce_connect:
    username: LukeSheard
  jwt:
    secure: u9fmU1Ded0ghOPqUBghjacxGTUI5w/4gA2pbTFj4acw3tvtCTvWR+VcBheLa+M7lKUlbYmttxh3VqFemTRu/RXoOXT+OUy8d4dAG1Dd53NuRAyCiP96oTOImKfOz6QW6TcA7IRo4+zqb/0S52g0rS9NM85WtG8D2W+RSo6V8qJdueswQRNYnKNCeBSZKvU3Ge3ViuUiBv3b8ULLM841ZflBA+3PkHxJMl1ziwYmJ7R5IB0wtcsLIdI9kW2hSJIyAwVbZqS3UVpIQPhW4kJibXaaFoHqemtzlPiGZ+PdiEkVUUvIaImpb9sTqQHTFjmOP60FntX5ANS3RnLtimUNmx48Y7FyYbNVHylqgq47qXGLuU742vdWA+4OkoqolWsQVMkY47uQ8+3dCxtfDhtOGNTyCNFpC8lr9fOp+SCx4Dcssn7UiQD3hg4C3TQYOldPP9SevzqkKk1JD6A5fg9iTgbDJ25iM/B7PHsYNKT1vSAQVrku8sQuZz9lPWxzZ2/vg+8fpHoF/JYk/HoYjZweZAt1WL7SHeAEDa1IKoQSESjVJeLhJ4noY5if3ueoFU1vj0yXrOjgnyvnZ3nT0Voth164Ldet87gVPuQg+uZYguiHB/Hu71YRkKjpIUX1xxPRBWqnifEOZBY1QsmnuoKKBDgyU1q8F4K1xTR3H/M4zMf0=
  at:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
- nvm use $TRAVIS_NODE_VERSION
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_script:
- npm run server:cov:publish
